What are the most demanded skills for the top 3 most popular roles?
Methodology
1. Clean up skill column
2. Calculate the skill count based on job_title_short
3. Calculate the skill percentage
4. Plot final findings

In [1]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  
import ast

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

#convert skill list column into a list
def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)  
    return skill_list  # Return the original NaN value

df['job_skills'] = df['job_skills'].apply(clean_list)

c:\Users\Greg\anaconda3\envs\Python_Data_Project_1_env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

In [2]:
df_UK = df[df['job_country'] == 'United Kingdom']

df_skills = df_UK.explode('job_skills')
df_skills[['job_title', 'job_skills']]

                                                job_title  job_skills
15                                          Data Engineer      python
15                                          Data Engineer         sql
15                                          Data Engineer    power bi
45                                    Senior Data Analyst         sql
45                                    Senior Data Analyst      python
...                                                   ...         ...
785642  Submission for the position: Data Engineer Sen...        qlik
785642  Submission for the position: Data Engineer Sen...  confluence
785642  Submission for the position: Data Engineer Sen...        jira
785676                              Senior Data Scientist           r
785676                              Senior Data Scientist      python

[167546 rows x 2 columns]

In [7]:
df_skills_count = df_skills.groupby(['job_skills', 'job_title_short']).size()
df_skills_count = df_skills_count.reset_index(name='skill_count')
df_skills_count.sort_values(by='skill_count', ascending=False, inplace=True)
df_skills_count

      job_skills            job_title_short  skill_count
1163         sql              Data Engineer         7050
915       python              Data Engineer         6462
916       python             Data Scientist         6329
88         azure              Data Engineer         4865
1162         sql               Data Analyst         4467
...          ...                        ...          ...
1368      vue.js          Software Engineer            1
1367      vue.js       Senior Data Engineer            1
514   javascript  Machine Learning Engineer            1
551        julia          Software Engineer            1
1418        zoom          Software Engineer            1

[1419 rows x 3 columns]

Create a list of top 3 roles

In [11]:
job_titles = df_skills_count['job_title_short'].unique().tolist()
job_titles = sorted(job_titles[:3])

job_titles

['Data Analyst', 'Data Engineer', 'Data Scientist']

Plot Skill Counts