In [22]:
# Importing Libraries
import pandas as pd
from datasets import load_dataset
import matplotlib.pyplot as plt  

# Loading Data
dataset = load_dataset('lukebarousse/data_jobs')
df = dataset['train'].to_pandas()

# Data Cleanup
df['job_posted_date'] = pd.to_datetime(df['job_posted_date'])

Calculate the projected salary next month

In [23]:
df[pd.notna(df['salary_year_avg'])]['salary_year_avg']

28        109500.0
77        140000.0
92        120000.0
100       228222.0
109        89000.0
            ...
785624    139216.0
785641    150000.0
785648    221875.0
785682    157500.0
785692    157500.0
Name: salary_year_avg, Length: 22003, dtype: float64

In [24]:
#to get projected salaries, with an inflation rate of 3%
#create a function

df_salary = df[pd.notna(df['salary_year_avg'])].copy()

def projected_salary(salary):
    return salary*1.03

df_salary['salary_year_inflated'] = df_salary['salary_year_avg'].apply(projected_salary)
df_salary[['salary_year_avg', 'salary_year_inflated']]

        salary_year_avg  salary_year_inflated
28             109500.0             112785.00
77             140000.0             144200.00
92             120000.0             123600.00
100            228222.0             235068.66
109             89000.0              91670.00
...                 ...                   ...
785624         139216.0             143392.48
785641         150000.0             154500.00
785648         221875.0             228531.25
785682         157500.0             162225.00
785692         157500.0             162225.00

[22003 rows x 2 columns]

In [25]:
#use apply method to convert job_skills column from a list to a string
#using ast method, abstract syntax trees
import ast
ast.literal_eval(df['job_skills'][1])

['r', 'python', 'sql', 'nosql', 'power bi', 'tableau']

In [26]:
#this can also be done for the entire column

import ast

def clean_list(skill_list):
    if pd.notna(skill_list):
        return ast.literal_eval(skill_list)  # Use skill_list parameter, not df['job_skills'][1]
    return skill_list  # Return the original NaN value

df['job_skills'] = df['job_skills'].apply(clean_list)
df['job_skills']

0                                                       NaN
1                [r, python, sql, nosql, power bi, tableau]
2         [python, sql, c#, azure, airflow, dax, docker,...
3         [python, c++, java, matlab, aws, tensorflow, k...
4         [bash, python, oracle, aws, ansible, puppet, j...
                                ...
785736    [bash, python, perl, linux, unix, kubernetes, ...
785737                               [sas, sas, sql, excel]
785738                                  [powerpoint, excel]
785739    [python, go, nosql, sql, mongo, shell, mysql, ...
785740                                          [aws, flow]
Name: job_skills, Length: 785741, dtype: object

In [35]:
#Assuming the senior roles get a 5% increase, where as the junior roles get a 3% increase in salary
#Meaning we would be affecting rows instead of columns

def projected_salary(row):
    if "Senior" in row['job_title_short']:
        return 1.05 * row['salary_year_avg']
    else:
        return 1.03 * row['salary_year_avg']

df_salary['salary_year_inflated'] = df_salary.apply(projected_salary, axis=1)

df_salary['salary_year_percentage'] = (df_salary['salary_year_inflated']/ df_salary['salary_year_avg'] - 1)*100
df_salary[['job_title_short', 'salary_year_avg', 'salary_year_inflated', 'salary_year_percentage']].head(30)

,job_title_short,salary_year_avg,salary_year_inflated,salary_year_percentage
28,Data Scientist,109500.00000,112785.000000,3.0
77,Data Engineer,140000.00000,144200.000000,3.0
92,Data Engineer,120000.00000,123600.000000,3.0
100,Data Scientist,228222.00000,235068.660000,3.0
109,Data Analyst,89000.00000,91670.000000,3.0
116,Data Scientist,114000.00000,117420.000000,3.0
146,Data Engineer,129500.00000,133385.000000,3.0
180,Data Analyst,90250.00000,92957.500000,3.0
212,Data Scientist,157500.00000,162225.000000,3.0
257,Data Scientist,103128.00000,106221.840000,3.0
307,Data Engineer,185000.00000,190550.000000,3.0
339,Data Engineer,195000.00000,200850.000000,3.0
380,Data Engineer,97500.00000,100425.000000,3.0
388,Data Engineer,89000.00000,91670.000000,3.0
410,Data Analyst,133285.00000,137283.550000,3.0
450,Data Scientist,157500.00000,162225.000000,3.0
495,Senior Data Engineer,168500.00000,176925.000000,5.0
520,Business Analyst,63000.00000,64890.000000,3.0
545,Data Engineer,80000.00000,82400.000000,3.0
571,Data Engineer,110000.00000,113300.000000,3.0
573,Senior Data Engineer,160000.00000,168000.000000,5.0
645,Business Analyst,125000.00000,128750.000000,3.0
654,Data Engineer,70000.00000,72100.000000,3.0
657,Senior Data Engineer,165000.00000,173250.000000,5.0
679,Software Engineer,317000.00000,326510.000000,3.0
704,Data Engineer,100000.00000,103000.000000,3.0
719,Data Engineer,111228.15625,114565.000938,3.0
726,Senior Data Engineer,173500.00000,182175.000000,5.0
733,Senior Data Engineer,160000.00000,168000.000000,5.0
762,Data Engineer,171000.00000,176130.000000,3.0